; Write a program to find the highest number in a series from location of 2000H to 2009H
; Store the result (highest number) at location 200AH


    LXI H, 2000H     ; INITIAL ADDRESS IN HL PAIR
    MVI C, 0AH       ; COUNT (NUMBERS IN THE SERIES)
    MVI A, 00H       ; CONSIDERING CURRENT HIGHEST NUMBER IS 00H
			
BACK: CMP M          ; INTERNALLY A - M (BUT DO NOT STORE RESULT ALSO DO NOT CHANGE A OR M, JUST UPDATE THE FLAG REGISTERS))
    JNC SKIP         ; IF NO CARRY THEN DO NO UPDATE THE A FOR THE HIGHEST NUMBER
    MOV A, M         ; UPDATE A IF M IS HIGHER THAN A
SKIP: INX H          ; UPDATING HL TO POINT TO THE ADDRESS OF NEXT NUMBER IN THE SERIES
    DCR C
    JNZ BACK 

    MOV M, A         ; STORE THE HIGHEST NUMBER IN THE FINAL ADDRESS POINTED BY HL
    
    HLT
